<?php

namespace ContainerFx9FtoU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SKWoSN8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sKWoSN8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sKWoSN8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'snappy' => ['privates', 'Knp\\Snappy\\Pdf', 'getPdfService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'snappy' => 'Knp\\Snappy\\Pdf',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
