<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container42xzSVB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container42xzSVB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container42xzSVB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container42xzSVB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container42xzSVB\App_KernelDevDebugContainer([
    'container.build_hash' => '42xzSVB',
    'container.build_id' => '2b0d426a',
    'container.build_time' => 1695336799,
], __DIR__.\DIRECTORY_SEPARATOR.'Container42xzSVB');
